// Code generated by gen.go DO NOT EDIT.

package main

import (
	_ "github.com/faceair/go-dnsmasq/middleware/accesslist"
	_ "github.com/faceair/go-dnsmasq/middleware/cache"
	_ "github.com/faceair/go-dnsmasq/middleware/edns"
	_ "github.com/faceair/go-dnsmasq/middleware/hostsfile"
	_ "github.com/faceair/go-dnsmasq/middleware/metrics"
	_ "github.com/faceair/go-dnsmasq/middleware/ratelimit"
	_ "github.com/faceair/go-dnsmasq/middleware/recovery"
	_ "github.com/faceair/go-dnsmasq/middleware/resolver"
)
